name: Key Generator Test

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts to be generated (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys to be generated (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        default: developermail
      key_type:
        description: 'Modes of operation'
        required: true
        type: choice
        options:
          - --key
          - --small-business-key
          - --vpn-codes
        default: --key
      os:
        description: 'Operating System of runner'
        required: true
        type: choice
        options:
        - macOS
        - Linux
        - Windows
        default: macOS
  #schedule:
    #- cron: "10 */12 * * *"

jobs:
  GenerateKey:
    runs-on: ${{ github.event.inputs.os == 'Linux' && 'ubuntu-latest' || github.event.inputs.os == 'Windows' && 'windows-latest' || 'macos-latest' }}
    steps:
      - name: Generate Keys and Accounts
        run: |
          # Determine if the workflow was triggered by a manual dispatch or schedule
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ACCOUNT=${{ github.event.inputs.account }}
            KEY=${{ github.event.inputs.key }}
            MAIL=${{ github.event.inputs.mail }}
            KEY_TYPE=${{ github.event.inputs.key_type }}
            OS=${{ github.event.inputs.os }}
          else
            # Default values for scheduled runs
            ACCOUNT=0
            KEY=1
            MAIL=developermail
            KEY_TYPE=--key
            OS=macOS
          fi

          #TOKEN=${{ secrets.TOKEN }}

          echo "Inputs determined as:"
          echo "ACCOUNT=${ACCOUNT}"
          echo "KEY=${KEY}"
          echo "MAIL=${MAIL}"
          echo "KEY_TYPE=${KEY_TYPE}"
          echo "OS=${OS}"

          # Clone the repository
          git clone https://github.com/shariful998765/ESET-KeyGen.git
          cd ESET-KeyGen || exit 1

          # Setup Python environment based on OS
          if [[ "${OS}" == "Windows" ]]; then
              python -m venv venv
              venv\Scripts\activate
          elif [[ "${OS}" == "macOS" ]]; then
              brew install python
              python3 -m venv venv
              source venv/bin/activate
          else
              sudo apt update
              sudo apt install -y python3-pip python3-venv
              python3 -m venv venv
              source venv/bin/activate
          fi

          pip install -r requirements.txt

          # Function to generate accounts
          function generate_accounts {
            seq 1 $1 | xargs -I {} -P $1 python3 main.py --chrome --account --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
          }

          # Function to generate keys
          function generate_keys {
            seq 1 $1 | xargs -I {} -P $1 python3 main.py --chrome ${KEY_TYPE} --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
          }

          # Generate based on input parameters
          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
              generate_accounts ${ACCOUNT} &
              generate_keys ${KEY}
              wait
              echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
              cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY || echo "No accounts generated." >> $GITHUB_STEP_SUMMARY
              echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
              cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY || echo "No keys generated." >> $GITHUB_STEP_SUMMARY
          elif [[ ${ACCOUNT} -ne 0 ]]; then
              generate_accounts ${ACCOUNT}
              echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
              cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY || echo "No accounts generated." >> $GITHUB_STEP_SUMMARY
          elif [[ ${KEY} -ne 0 ]]; then
              generate_keys ${KEY}
              echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
              cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY || echo "No keys generated." >> $GITHUB_STEP_SUMMARY
          fi

          # Deactivate the virtual environment
          deactivate
